=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/acl.dtd
<!ELEMENT acl (Aces)>
    <!ATTLIST acl aclname CDATA #REQUIRED>
    <!ELEMENT Aces (Ace*)>    
        <!ELEMENT Ace (Principal, accessType, Privilege, ResourceObject)>
            <!ATTLIST Ace id ID #REQUIRED>
            <!ELEMENT Principal EMPTY>
                <!ATTLIST Principal idref IDREF #IMPLIED>
            <!ELEMENT accessType (#PCDATA)>
            <!ELEMENT Privilege EMPTY>
                <!ATTLIST Privilege idref IDREF #IMPLIED>
            <!ELEMENT ResourceObject EMPTY>
                <!ATTLIST ResourceObject idref IDREF #REQUIRED>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/pkg/Ruby-ACL-0.0.1/lib/src_files/acl.xml
<!DOCTYPE acl SYSTEM "acl.dtd">
<acl aclname="my_first_acl">
    <Aces>
        <Ace id="a987">
            <Principal idref="Klubicko"/>
            <accessType>allow</accessType>
            <Privilege idref="KUTALET"/>
            <ResourceObject idref="456"/>
        </Ace>
        <Ace id="a894">
            <Principal idref="Users"/>
            <accessType>allow</accessType>
            <Privilege idref="SELECT"/>
            <ResourceObject idref="852"/>
        </Ace>
    </Aces>
</acl>
