=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/Principals.dtd
<!ELEMENT Principals (Groups, Individuals)>
    <!ELEMENT Groups (Group+)>
    <!ELEMENT Group (membership)>
        <!ATTLIST Group id ID #REQUIRED>
    <!ELEMENT membership (mgroup*)>
    <!ELEMENT mgroup EMPTY>
        <!ATTLIST mgroup idref IDREF #REQUIRED>

    <!ELEMENT Individuals (Individual*)>
    <!ELEMENT Individual (membership)>
        <!ATTLIST Individual id ID #IMPLIED>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/Principals.xml
<?xml version="1.0"?>
<!DOCTYPE Principals SYSTEM "Principals.dtd">
<Principals>
    <Groups>
        <Group id="ALL">
            <membership/>
        </Group>
        <Group id="Developers">
            <membership>    <!-->Developers are members of Administrators<!-->
                <mgroup idref="Administrators"/>
            </membership>
        </Group>
        <Group id="Administrators">
            <membership>
                <mgroup idref="ALL"/>
            </membership>
        </Group>
        <Group id="Users">
            <membership>
                <mgroup idref="ALL"/>
            </membership>
        </Group>
    </Groups>
    <Individuals>
        <Individual id="sirljan">
            <membership>
                <mgroup idref="Users" />
                <mgroup idref="Developers" />
            </membership>
        </Individual>
        <Individual id="Klubicko">
            <membership>
                <mgroup idref="Users"/>
            </membership>
        </Individual>
    </Individuals>
</Principals>
