=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/Privileges.dtd
<!ELEMENT Privileges (Privilege+)>
    <!ELEMENT Privilege (membership)>
        <!ATTLIST Privilege id ID #REQUIRED>
    <!ELEMENT membership (mgroup*)>
        <!ELEMENT mgroup EMPTY>
        <!ATTLIST mgroup idref IDREF #REQUIRED>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/Privileges.xml
<!DOCTYPE Privileges SYSTEM "Privileges.dtd">
<Privileges>
    <Privilege id="ALL_PRIVILEGES">
        <membership/>
    </Privilege>
    <Privilege id="ALTER">
        <membership>
            <mgroup idref="ALL_PRIVILEGES" />
        </membership>
    </Privilege>
    <Privilege id="CREATE">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="DELETE">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="DROP">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="FILE">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="INDEX">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="INSERT">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="PROCESS">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="REFERENCES">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="RELOAD">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="SELECT">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="SHUTDOWN">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="UPDATE">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
    <Privilege id="USAGE">
        <membership>             
            <mgroup idref="ALL_PRIVILEGES" />         
        </membership>
    </Privilege>
</Privileges>
