=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/acl.dtd
<!ELEMENT acl (Principals, Privileges, ResourceObjects, ACEs)>
    <!ATTLIST acl aclname CDATA #REQUIRED>
<!ELEMENT Principals (Groups, Individuals)>
    <!ELEMENT Groups (group*)>
    <!ELEMENT group (membership?)>
        <!ATTLIST group id ID #REQUIRED>
    <!ELEMENT membership (group+)>
    <!ELEMENT group EMPTY>
        <!ATTLIST group idref IDREF #REQUIRED>
    <!ELEMENT Individuals (principal*)>
    <!ELEMENT principal (membership?)>
        <!ATTLIST group id ID #REQUIRED>
    <!ELEMENT membership (group+)>
    <!ELEMENT group EMPTY>
        <!ATTLIST group idref IDREF #REQUIRED>
<!ELEMENT Privileges (privileges+)>
        <!ATTLIST privilege id ID #REQUIRED>
    <!ELEMENT privilege (membership)>
    <!ELEMENT membership (privilege*)>
        <!ATTLIST privilege idref IDREF #REQUIRED>
<!ELEMENT ResourceObjects (resourceObject)>
    <!ELEMENT resourceObject ANY>
        <!--ELEMENT ANY #PCDATA-->
        <!ATTLIST resourceObject id ID #REQUIRED>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/acl.xml
<!DOCTYPE acl SYSTEM "acl.dtd">
<acl aclname="my_first_acl">
    <Principals>
        <Groups>
            <group id="all"/>
            <group id="Developers">
                <membership>    <!-->Developers are members of Administrators<!-->
                    <group idref="Administrators"/>
                </membership>
            </group>
            <group id="Administrators">
                <membership/>
            </group>
            <group id="Users">
                <membership>
                    <group idref="all"/>
                </membership>
            </group>
        </Groups>
        <Individuals>
            <principal id="sirljan">
                <membership>
                    <group idref="Users" />
                    <group idref="Developers" />
                </membership>
            </principal>
            <principal id="Klubicko">
                <membership>
                    <group idref="Users"/>
                </membership>
            </principal>
        </Individuals>

    </Principals>
    
    <Privileges>
        <privilege id="ALL PRIVILEGES"/>
            <membership/>
        <privilege id="ALTER">
            <membership/>
        </privilege>
        <privilege id="CREATE">
            <membership/>
        </privilege>
        <privilege id="DELETE">
            <membership/>
        </privilege>
        <privilege id="DROP">
            <membership/>
        </privilege>
        <privilege id="FILE">
            <membership/>
        </privilege>
        <privilege id="INDEX">
            <membership/>
        </privilege>
        <privilege id="INSERT">
            <membership/>
        </privilege>
        <privilege id="PROCESS">
            <membership/>
        </privilege>
        <privilege id="REFERENCES">
            <membership/>
        </privilege>
        <privilege id="RELOAD">
            <membership/>
        </privilege>
        <privilege id="SELECT">
            <membership/>
        </privilege>
        <privilege id="SHUTDOWN">
            <membership/>
        </privilege>
        <privilege id="UPDATE">
            <membership/>
        </privilege>
        <privilege id="USAGE">
            <membership/>
        </privilege>
    </Privileges>
    
    <ResourceObjects>    
        <resourceObject id="456">
            <Kosik>Pleteny</Kosik>
        </resourceObject>
        <resourceObject id="963">
            <Les>cernocerny</Les>
        </resourceObject>
        <resourceObject id="852">
            <docAddress>cities/cities.xml</docAddress>
        </resourceObject>
    </ResourceObjects>
    
    <ACEs>
        <ace id="987">
            <principal idref="Klubicko"/>
            <accessType>allow</accessType>
            <privilege idref="KUTALET"/>
            <resourceObject idref="456"/>
        </ace>
        <ace id="894">
            <principal idref="Users"/>
            <accessType>allow</accessType>
            <privilege idref="SELECT"/>
            <resourceObject idref="852"/>
        </ace>
            
    </ACEs>
</acl>
