=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/aclpokus.dtd
<!ELEMENT acl (Principals, Privileges, ResourceObjects, ACEs)>
    <!ATTLIST acl aclname CDATA #REQUIRED>
<!ELEMENT Principals (Groups,Individuals)>
    <!ELEMENT Groups (group*)>
    <!ELEMENT group (membership+)>
        <!ATTLIST group id ID #REQUIRED>
    <!ELEMENT membership ANY>    
    <!ELEMENT Individuals ANY>
<!ELEMENT Privileges ANY>
<!ELEMENT ResourceObjects ANY>
<!ELEMENT ACEs ANY>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/aclgen.xml
<!DOCTYPE acl SYSTEM "aclpokus.dtd">
<acl aclname="my_first_acl">
    <Principals>
        <Groups>
            <group id="all">
                <membership/>
            </group> 
            <group id="Developers">
                <membership>    <!--Developers are members of Administrators-->
                    <group idref="Administrators"/>
                </membership>
            </group>
            <group id="Administrators">
                <membership/>
            </group>
            <group id="Users">
                <membership/>
            </group>
        </Groups>
        <Individuals>
        </Individuals>

    </Principals>
    
    <Privileges>
        
    </Privileges>
    
    <ResourceObjects>    

    </ResourceObjects>
    
    <ACEs>

            
    </ACEs>
</acl>
