=== dpruessner/Ruby-ACL/Documents/CD/src/Ruby-ACL/src_files/ResourceObjects.dtd
<!ELEMENT ResourceObjects (ResourceObject*)>
    <!ELEMENT ResourceObject (type, address, owner)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT owner EMPTY>
            <!ATTLIST owner idref IDREF #REQUIRED>
        <!ATTLIST ResourceObject id ID #REQUIRED>

=== dpruessner/Ruby-ACL/Src/Ruby-ACL/lib/src_files/ResourceObjects.xml
<!DOCTYPE ResourceObjects SYSTEM "ResourceObjects.dtd">    
<ResourceObjects>    
    <ResourceObject id="r456">
        <type>Kosik</type>
        <address>Pleteny</address>
        <owner idref="Klubicko"/>
    </ResourceObject>
    <ResourceObject id="r963">
        <type>Les</type>
        <address>/V_Hodkovickach</address>
        <owner idref="sirljan"/>
    </ResourceObject>
    <ResourceObject id="r8525">
        <type>doc</type>
        <address>(/db/cities/cities.xml)/cities/*</address>
        <owner idref="sirljan"/>
    </ResourceObject>
    <ResourceObject id="r852">
        <type>doc</type>
        <address>/db/cities/cities.xml</address>
        <owner idref="nikdo"/>
    </ResourceObject>
    <ResourceObject id="r111111111">
        <type>doc</type>
        <address>/db/temp</address>
        <owner idref="nikdo"/>
    </ResourceObject>
    <ResourceObject id="r222222222">
        <type>doc</type>
        <address>/db/temp/test</address>
        <owner idref="nikdo"/>
    </ResourceObject>
    <ResourceObject id="r333333333">
        <type>doc</type>
        <address>/db/temp/test/hokus</address>
        <owner idref="nikdo"/>
    </ResourceObject>
    <ResourceObject id="r444444444">
        <type>doc</type>
        <address>/db/temp/test/*</address>
        <owner idref="nikdo"/>
    </ResourceObject>
</ResourceObjects>
